version: '3.7'

services:
  # CMS
  cms-bkhill:
    image: greenapps/new-cms-clone:bkhill
    container_name: cms-clone-bkhill
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    ports:
      - '3201:80'
    # volumes:
    #   - '.:/app'
    restart: always
    networks:
      - bkhill_network
networks:
  bkhill_network:
    driver: bridge
