version: '3.7'

services:
  # CMS
  cms-goodvina:
    image: greenapps/new-cms-clone:goodvina
    container_name: cms-clone-goodvina
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    ports:
      - '3301:80'
    # volumes:
    #   - '.:/app'
    restart: always
    networks:
      - goodvina_network
networks:
  goodvina_network:
    driver: bridge
